FIX: remove release running issue

diff --git a/bin/sake-release b/bin/sake-release
--- a/bin/sake-release
+++ b/bin/sake-release
@@ -265,36 +265,36 @@ else
     vendor/bin/sake dev/build flush=all
 fi
 
-if [ "$SS_ENVIRONMENT_TYPE" != "dev" ]; then
-    # build
-    if [ "$SS_RELEASE_FRONT_END" != "false" ]; then
-        FILE_PATH="./.env"
-        BASE_URL=$(grep -oP 'SS_BASE_URL="\K[^"]+' $FILE_PATH)
-        # Check if BASE_URL was successfully set
-        if [ -z "$BASE_URL" ]; then
-            echo "Error: SS_BASE_URL is not set in $FILE_PATH. Exiting."
-            exit 1
-        fi
-        # Remove any trailing slash
-        BASE_URL="${BASE_URL%/}"
-        NEW_URL="${BASE_URL}/dev/?flush=all"
+# if [ "$SS_ENVIRONMENT_TYPE" != "dev" ]; then
+#     # build
+#     if [ "$SS_RELEASE_FRONT_END" != "false" ]; then
+#         FILE_PATH="./.env"
+#         BASE_URL=$(grep -oP 'SS_BASE_URL="\K[^"]+' $FILE_PATH)
+#         # Check if BASE_URL was successfully set
+#         if [ -z "$BASE_URL" ]; then
+#             echo "Error: SS_BASE_URL is not set in $FILE_PATH. Exiting."
+#             exit 1
+#         fi
+#         # Remove any trailing slash
+#         BASE_URL="${BASE_URL%/}"
+#         NEW_URL="${BASE_URL}/dev/?flush=all"
 
-        if [ "$SS_ENVIRONMENT_TYPE" == "test" ]; then
-            sed -i 's/SS_ENVIRONMENT_TYPE="test"/SS_ENVIRONMENT_TYPE="dev"/g' $FILE_PATH
-        elif [ "$SS_ENVIRONMENT_TYPE" == "live" ]; then
-            sed -i 's/SS_ENVIRONMENT_TYPE="live"/SS_ENVIRONMENT_TYPE="dev"/g' $FILE_PATH
-        fi
+#         # if [ "$SS_ENVIRONMENT_TYPE" == "test" ]; then
+#         #     sed -i 's/SS_ENVIRONMENT_TYPE="test"/SS_ENVIRONMENT_TYPE="dev"/g' $FILE_PATH
+#         # elif [ "$SS_ENVIRONMENT_TYPE" == "live" ]; then
+#         #     sed -i 's/SS_ENVIRONMENT_TYPE="live"/SS_ENVIRONMENT_TYPE="dev"/g' $FILE_PATH
+#         # fi
 
-        wget -O - $NEW_URL
+#         # wget -O - $NEW_URL
 
-        # Switch SS_ENVIRONMENT_TYPE back to its original value
-        if [ "$SS_ENVIRONMENT_TYPE" == "test" ]; then
-            sed -i 's/SS_ENVIRONMENT_TYPE="dev"/SS_ENVIRONMENT_TYPE="test"/g' $FILE_PATH
-        elif [ "$SS_ENVIRONMENT_TYPE" == "live" ]; then
-            sed -i 's/SS_ENVIRONMENT_TYPE="dev"/SS_ENVIRONMENT_TYPE="live"/g' $FILE_PATH
-        fi
-    fi
-fi
+#         # # Switch SS_ENVIRONMENT_TYPE back to its original value
+#         # if [ "$SS_ENVIRONMENT_TYPE" == "test" ]; then
+#         #     sed -i 's/SS_ENVIRONMENT_TYPE="dev"/SS_ENVIRONMENT_TYPE="test"/g' $FILE_PATH
+#         # elif [ "$SS_ENVIRONMENT_TYPE" == "live" ]; then
+#         #     sed -i 's/SS_ENVIRONMENT_TYPE="dev"/SS_ENVIRONMENT_TYPE="live"/g' $FILE_PATH
+#         # fi
+#     fi
+# fi
 
 # Ping release URL if set
 [ -n "$FIA_RELEASE_PING_URL" ] && wget -S -qO- "${FIA_RELEASE_PING_URL}$(git rev-parse HEAD)"
