PATCH: clean up

diff --git a/bin/sake-release b/bin/sake-release
--- a/bin/sake-release
+++ b/bin/sake-release
@@ -4,7 +4,7 @@
 display_help() {
     rm release-running -f
     echo
-    echo "Usage: vendor/bin/sake-release [environment type...] [branch...]" >&2
+    echo "Usage: vendor/bin/sake-release [branch...]" >&2
     echo
     echo "   -a                Create a backup, default is NO"
     echo "   -e                Environment type, overrule type set in .env file."
@@ -14,35 +14,32 @@ display_help() {
     echo "   -u                In dev mode, run composer update rather than composer install"
     echo "   -h                Display this help message and exit"
     echo
-    echo "Example (run from project root directory on the live server):"
+    echo "Example (run from project root directory on the live server)"
+    echo "It will make a backup and then release the latest version of the production branch"
     echo
-    echo "   vendor/bin/sake-release"
+    echo "   vendor/bin/sake-release -a"
     echo
     echo
     echo "Other examples:"
 
     echo " # release the develop branch locally"
-    echo "   vendor/bin/sake-release dev -e dev     "
+    echo " # (-e dev is optional, it will check SS_ENVIRONMENT_TYPE in .env))"
+    echo "   vendor/bin/sake-release develop -e dev     "
     echo ""
 
-    echo " # release the develop branch on a test site"
-    echo "   vendor/bin/sake-release test"
+    echo " # release the my-feature-branch branch"
+    echo "   vendor/bin/sake-release my-feature-branch"
     echo ""
 
-    echo " # release the my-feature-branch branch on a test site"
-    echo "   vendor/bin/sake-release test my-feature-branch"
+    echo " # release the development branch, set permissions (www-data), run composer update"
+    echo "   vendor/bin/sake-release -p -u"
     echo ""
 
-    echo " # ON DEV: release the development branch, set permissions (www-data), run composer update"
-    echo "   vendor/bin/sake-release -p -u "
-    echo ""
-
-    echo " # ON PROD: make a backup, release feature/awesome, run as www-data"
-    echo "   vendor/bin/sake-release live feature/awesome -a  -w www-data"
+    echo " # make a backup, release feature/awesome, run as www-data"
+    echo "   vendor/bin/sake-release live feature/awesome -a -w www-data"
 
     echo
     echo
-    # add more help options here
     exit 1
 }
 
@@ -68,6 +65,7 @@ wwwDataUser=''
 setPermissions=false
 composerUpdate=false
 
+# get flags
 while getopts ":ae:w:puh" opt; do
     case ${opt} in
     a)
@@ -109,8 +107,8 @@ done
 shift $((OPTIND - 1))
 
 # Determine git branch based on environment if not provided
-branch_name=$2
-if [ -z "$2" ]; then
+branch_name=$1
+if [ -z "$1" ]; then
     if [ "$SS_ENVIRONMENT_TYPE" == "live" ]; then
         branch_name="production"
     elif [ "$SS_ENVIRONMENT_TYPE" == "dev" ] || [ "$SS_ENVIRONMENT_TYPE" == "test" ]; then
@@ -124,6 +122,21 @@ if git show-ref --verify --quiet refs/heads/$branch_name; then
 else
     echo "Branch '$branch_name' does not exist."
     git fetch --all
+    exit 1
+fi
+
+# Test env type: dev / test / live
+if [ "$SS_ENVIRONMENT_TYPE" == "dev" ]; then
+    echo "DEV environment"
+elif [ "$SS_ENVIRONMENT_TYPE" == "test" ]; then
+    echo "TEST environment"
+elif [ "$SS_ENVIRONMENT_TYPE" == "live" ]; then
+    echo "LIVE environment"
+else
+    echo "Invalid argument. "
+    echo "... Please specify 'dev', 'test',  or 'live' using the -e flag "
+    echo "... or make sure it is set in the env file (SS_ENVIRONMENT_TYPE)"
+    rm release-running -f
     exit 1
 fi
 
@@ -170,35 +183,22 @@ date >>release.log
 git describe --all --long >>release.log
 
 # get git
-# Git actions with chosen branch
 git checkout $branch_name
+# Git actions with chosen branch
 git pull origin $branch_name
-
-# Provide a flag: dev / test / live
-if [ "$SS_ENVIRONMENT_TYPE" == "dev" ]; then
-    echo "DEV environment"
-elif [ "$SS_ENVIRONMENT_TYPE" == "test" ]; then
-    echo "TEST environment"
-elif [ "$SS_ENVIRONMENT_TYPE" == "live" ]; then
-    echo "LIVE environment"
-else
-    echo "Invalid argument. "
-    echo "... Please specify 'dev', 'test',  or 'live' "
-    echo "... or make sure it is set in the env file (SS_ENVIRONMENT_TYPE)"
-    exit 1
-fi
 
 # run composer
 if [ "$SS_ENVIRONMENT_TYPE" == "dev" ]; then
-
-    # composer update
-    composer install --prefer-source
+    if [ "$composerUpdate" == true ]; then
+        composer update --prefer-source
+    else
+        composer install --prefer-source
+    fi
 else
     composer install --prefer-dist --no-dev
 fi
 
 # set permissions
-
 if [ "$setPermissions" == true ]; then
 
     # remove obsolete folders
@@ -220,7 +220,7 @@ if [ "$setPermissions" == true ]; then
     sudo chown $(whoami):$wwwDataUser . -R
 
     sudo chown $wwwDataUser ./public/assets -R
-    sudo chown $wwwDataUser ./.graphql-generated/ -R
+    sudo chown $wwwDataUser ./.graphql-generated -R
     sudo chown $wwwDataUser ./public/_graphql -R
     # files ...
     if [ -f ./public/admin.types.graphql ]; then
