FIX: WIP

diff --git a/bin/sake-release b/bin/sake-release
--- a/bin/sake-release
+++ b/bin/sake-release
@@ -54,7 +54,12 @@ recordcommit() {
     } >>release.log
 }
 
-source ./.env # Load environment variables
+if [ -f ./.env ]; then
+    source ./.env
+else
+    echo "Error: .env file not found."
+    exit 1
+fi
 
 # Default variables
 branch_name=""
