FIX: fixing bugs in syntax

diff --git a/bin/sake-release b/bin/sake-release
--- a/bin/sake-release
+++ b/bin/sake-release
@@ -89,7 +89,7 @@ fi
 if [ -n "$SS_IMPORT_SSPAK_EVERY_TIME" ] && [ -f "$SS_IMPORT_SSPAK_EVERY_TIME" ]; then
     echo "Importing sspak file $SS_IMPORT_SSPAK_EVERY_TIME"
     import=true
-else
+elif [ -n "$SS_IMPORT_SSPAK_EVERY_TIME" ]; then
     echo "SS_IMPORT_SSPAK_EVERY_TIME is set but file does not exist or is invalid."
 fi
 if [ -z "$SS_ENVIRONMENT_TYPE" ]; then
@@ -155,6 +155,8 @@ while [[ $# -gt 0 ]]; do
         ;;
     esac
 done
+# Define a cleanup function and set the trap
+trap 'echo "An error occurred. "; rm -f release-running; exit 1' ERR
 
 # If release is running, wait
 if [ -f "release-running" ]; then
@@ -203,6 +205,7 @@ if [ "$backup" = true ] || [ "$import" = true ]; then
     echo "Backup complete, please check ./__backups/backup.sspak"
     if [ "$backupOnly" = true ]; then
         echo "Backup complete, please check ./__backups/backup.sspak"
+        rm release-running -f
         exit 0
     fi
 fi
@@ -221,6 +224,7 @@ if [ "$import" = true ]; then
     ./__backups/ssbak load "$SS_IMPORT_SSPAK_EVERY_TIME" .
     echo "Import complete."
     if [ "$importOnly" = true ]; then
+        rm release-running -f
         exit 0
     fi
 fi
